apiVersion: apps/v1
kind: Deployment
metadata:
	name: ads
spec:
	replicas: 2
	selector:
		matchLabels:
			app: ads
	template:
		metadata:
			labels:
				app: ads
		spec:
			containers:
				- name: ads
			image: 
			env:
				- name: AWS_ACCESS_KEY_ID
				  value: 
				- name: AWS_SECRET_ACCESS_KEY
				  value:
			ports:
			- containerPorter: 8080